### ISSUE TITLE
A metric named clnt.dispatcher.serial.queue_size already exists

### ISSUE THREAD

**Issue by GoldenZero** [rlazoti/finagle-metrics#8]
Hey, 

Even after applying the synchronized block for adding Gauge, I still get the exception about metric name is already exists 
`
 java.lang.IllegalArgumentException: A metric named clnt.dispatcher.serial.queue_size already exists
 	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91)
 	at com.twitter.finagle.metrics.MetricsStatsReceiver$MetricGauge.<init>(MetricsStatsReceiver.scala:46)
 	at com.twitter.finagle.metrics.MetricsStatsReceiver.addGauge(MetricsStatsReceiver.scala:76)
 	at com.twitter.finagle.stats.StatsReceiverProxy.addGauge(StatsReceiverProxy.scala:10)
 	at com.twitter.finagle.stats.StatsReceiverProxy.addGauge$(StatsReceiverProxy.scala:10)
 	at com.twitter.finagle.stats.LoadedStatsReceiver$.addGauge(LoadedStatsReceiver.scala:9)
 	at com.twitter.finagle.stats.NameTranslatingStatsReceiver.addGauge(NameTranslatingStatsReceiver.scala:32)
 	at com.twitter.finagle.stats.StatsReceiverProxy.addGauge(StatsReceiverProxy.scala:10)
 	at com.twitter.finagle.stats.StatsReceiverProxy.addGauge$(StatsReceiverProxy.scala:10)
 	at com.twitter.finagle.stats.ClientStatsReceiver$.addGauge(LoadedStatsReceiver.scala:46)
`
 Any idea what could cause this case?

**Comment by rlazoti** [comment]
@GoldenZero are you using the latest finagle-metrics version (0.0.9)?

**Comment by GoldenZero** [comment]
Yes, it's version 0.0.9 with  Codahale Metrics library 3.2.3 and finagle 6.45

**Comment by rlazoti** [comment]
@GoldenZero There's a new release 0.0.12 to fix it.
Please, let me know if you continue to get this exception.
